
road='road'
bridge='bridge'
name='name'
roadName='roadName'
km='km'
lrp='lrp'
lrpType='type'
lrpname='LRPName'
length='length'
condition='condition'
structureNr='structureNr'
roadName='roadName'
chainage='chainage'
width='width'
constructionYear='constructionYear'
spans='spans'
zone='zone'
circle='circle'
division='division'
subDivision='sub-division'
lat='lat'
lon='lon'
offset='offset'
referenceLrp = 'referenceLrp'

estimatedLoc='EstimatedLoc'
